### ISSUE TITLE
require('gstreamer-superficial') hangs

### ISSUE THREAD

**Issue by tvandergeer** [dturing/node-gstreamer-superficial#2]
This evening I tried to get your node module to work because I was looking for a way to "interact" with gstreamer. And nodejs is currently my language of choice... The module compiled fine once I had the developer version of Gstreamer in place and made sure that PKG_CONFIG_PATH was pointing to the correct dir. (For some reason I couldn't get it to install globally using 'npm install -g' but that's not my main concern right now)

Next stop was to run an example. Once I issued the command to run an example no errors pop up. It just doesn't do anything. That's when I started the example app using node-debug. The step-debugger learned me that once it hits the 
```
require('..');
```
line it "hangs". The debugger doesn't hit the next line. It seems that it takes forever to load the gstreamer-superficial module. What could be wrong?

Note that I'm running Gstreamer 1.10.2 on OSX with node v4.6.0.

**Comment by dturing** [comment]
I've tried to reproduce this, i run node v6.8.1, gstreamer 1.10.2 from homebrew (`brew install gstreamer gst-plugins-base gst-plugins-good`). i didn't have to set PKG_CONFIG_PATH (probably thanks to homebrew).

the basic-pipeline example fails because i dont have the "textoverlay" plugin, and "autovideosink" seems to fail from within node. if i replace the pipeline to read "videotestsrc ! osxvideosink", it works.

the bus.js and appsink.js examples worked out of the box; the streaming example is know to be broken.

did you manage to get it working, or did you give up? if the problem persists, you might try installing gstreamer from homebrew or updating node, although i don't think that will change much about your issue.

**Comment by tvandergeer** [comment]
Yes, I managed to get this to work last night after reading your post. Eventually reinstalling using homebrew did the trick, but I had to remove the previous installation manually. And it didn't work untill I installed the gst-plugins-base as well. Thanks for your response!

**Comment by dturing** [comment]
Great, thanks for your feedback.

Just for the history books: by now i've switched back from gstreamer-via-homebrew to installing the "official" gstreamer OSX PKGs, and that also works fine for me (though i need to export PKG_CONFIG_PATH=/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/pkgconfig/)
